apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-agent-iac-template
  title: GCP - Agent IaC
  description: Template to deploy a new GCP Agent
  tags:
    - gcp
    - agent
    - template
spec:
  owner: group:catalog-admin
  type: agent

  parameters:
    - title: General Details
      required:
        - owner
        - name
        - description
        - agent_aliasname
        - agent_aliasdescription
        - instruction
        - llm_name
        - region
        - staging_bucket_name
      properties: 
        name:
          title: Agent Name
          type: string
          description: Provide the Agent Name
          pattern: "^(?=.{3,63}$)[a-z]([a-z0-9_]*[a-z0-9])?$" # Agent name must be a valid identifier. 3-63 chars, starts with a lowercase letter, can contain lowercase letters, numbers, and underscores, and ends with a letter or number.
          ui:help: "Must be 3–63 characters, start with a lowercase letter, can contain lowercase letters, numbers, and underscores, and end with a letter or number."

        description:
          title: Description
          type: string
          description: Provide the Description
          maxLength: 200

        agent_aliasname:
          type: string
          title: Agent Alias Name
          description: Provide the Agent Alias Name
          pattern: "^(?=.{3,63}$)[a-z]([a-z0-9_]*[a-z0-9])?$" # Agent name must be a valid identifier. 3-63 chars, starts with a lowercase letter, can contain lowercase letters, numbers, and underscores, and ends with a letter or number.
          ui:help: "Must be 3–63 characters, start with a lowercase letter, can contain lowercase letters, numbers, and underscores, and end with a letter or number."

        agent_aliasdescription:
          type: string
          title: Agent Alias Description
          description: Provide the Agent Alias Description

        instruction:
          title: Instruction
          type: string
          description: Provide the Instruction
          #minLength: 40

        region:
          title: Region
          type: object
          ui:field: custom_dropdown
          description: Select the Region
          apiPath: /api/ai-components/regions/
          attrKey: regionname
          disableIfValueExistsFor: name

        llm_name:
          title: Model Name
          type: object
          ui:field: custom_dropdown
          description: Select the Model
          apiPath: /api/ai-components/models/?provider_id=3&model_type=LLM%20Model
          attrKey: modelname
          requiredData:
            - key: region.value
              queryStringKey: region_name
              title: Region

        staging_bucket_name:
          title: Staging Bucket Name
          type: string
          description: "GCS bucket name for staging. Artifacts will be stored at gs://{BUCKET_NAME}/{AGENT_DISPLAY_NAME}/"
          pattern: "^(?=.{3,63}$)[a-z0-9](?:[a-z0-9._-]{1,61}[a-z0-9])$"
          ui:help: "Must be 3–63 characters, start with a lowercase letter, end with a lowercase letter or number, and can include lowercase letters, numbers, dots, dashes, or underscores."

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
            - Group
        lifecycle:
          title: Lifecycle
          type: string
          description: Provide the Lifecycle
          enum:
            - development
            - staging
            - production
          default: development
      
        mcp_server_url:
          title: MCP Server Name
          type: object
          ui:field: custom_dropdown
          description: Select the MCP Server to use
          apiPath: /api/ai-components/mcp-details/?provider_id=3&is_ready=true
          attrKey: mcpname
          valueFields: [mcpname]
          requiredData:
            - key: region.value
              queryStringKey: region_name
              title: Region
          versionDetails:
            nestedKey: versions
            attrKey: mcpurl
            valueFields: [ mcpurl, versionid ]
            title: MCP Server URL

        enable_guardrail:
          title: Enable Guardrail
          type: boolean
          default: true
          ui:widget: checkbox

      errorMessage:
        properties:
          name: "Agent name must be 3–63 characters, start with a lowercase letter, can contain lowercase letters, numbers, and underscores, and end with a letter or number."
          instruction: "must contain atleast 40 characters"
          agent_aliasname: "should start with a lowercase letter and can contain lowercase letters, numbers, and underscores; and end with a lowercase letter or number"
          staging_bucket_name: "Bucket name must be 3–63 characters, start with a lowercase letter, end with a lowercase letter or number, and can include lowercase letters, numbers, dots, dashes, or underscores."

      dependencies:
        enable_guardrail:
          allOf:
            - if:
                properties:
                  enable_guardrail:
                    const: true
              then:
                properties:
                  guardrail_name:
                    title: Guardrail Name
                    type: object
                    ui:field: custom_dropdown
                    description: Select the Guardrail to use
                    apiPath: /api/ai-components/guardrails-details/?provider_id=3&is_ready=true
                    attrKey: guardrailname
                    valueFields: [guardrailname]
                    requiredData:
                      - key: region.value
                        queryStringKey: region_name
                        title: Region
                    versionDetails:
                      nestedKey: versions
                      attrKey: versionid
                      valueFields: [ guardrailurl, versionid ]
                      title: Version ID
                required:
                  - guardrail_name


    - title: Knowledge Base Details
      ui:order:
        - enable_rag
        - rag_entities
      properties:
        enable_rag:
          title: Enable rag
          type: boolean
          default: false
          widget: switch
          ui:field: CustomCheckBoxExtension
      dependencies:
        enable_rag:
          allOf:
            - if:
                properties:
                  enable_rag:
                    const: true
              then:
                properties:
                  rag_entities:
                    title: Rag entity
                    type: array
                    minItems: 1
                    maxItems: 1
                    ui:options:
                      orderable: false
                    items:
                      type: object
                      properties:
                        rag_details:
                          title: RAG Details
                          type: object
                          ui:field: custom_dropdown
                          description: Select the RAG (Fetches the RAG ID)
                          apiPath: /api/ai-components/vectorized-dataset/?provider_id=3&is_ready=true
                          attrKey: datasetname
                          valueFields: [ datasetname, vectorizeddatasetbaseid ]
                          disableIfValueExistsFor: name
                          requiredData:
                            - key: region.value
                              queryStringKey: region_name
                              title: Region
                      required:
                        - rag_details

    - title: Monitoring and Evaluation
      properties:
        enable_groundtruth:
          title: Enable Ground Truth
          type: boolean
          default: false
          ui:widget: checkbox
        enable_general_groundtruth:
          title: Enable General Ground Truth
          type: boolean
          default: false
          ui:widget: checkbox
        enable_arize_evaluation:
          title: Enable Arize Evaluation
          type: boolean
          default: true
          ui:widget: hidden

      dependencies:
        enable_groundtruth:
          allOf:
            - if:
                properties:
                  enable_groundtruth:
                    const: true
              then:
                properties:
                  groundtruth:
                    title: Ground Truth Dataset RAG
                    type: object
                    ui:field: custom_dropdown
                    apiPath: /api/ai-components/ground-truth/
                    attrKey: groundtruth_name
                    valueFields: [groundtruth_name]
                    versionDetails:
                        nestedKey: versions
                        attrKey: versionid
                        valueFields: [ modelname, versionid ]
                        title: Version ID
        enable_general_groundtruth:
          allOf:  
            - if:
                properties: 
                  enable_general_groundtruth:
                    const: true
              then:
                properties:
                  general_groundtruth:
                    title: General Ground Truth 
                    type: object
                    ui:field: custom_dropdown
                    apiPath: /api/ai-components/general-ground-truth/
                    attrKey: general_groundtruth_name
                    valueFields: [ general_groundtruth_name, modelname ]

        enable_arize_evaluation:
          allOf:
            - if:
                properties:
                  enable_arize_evaluation:
                    const: true
              then:
                properties:
                  arize_model_name:
                    title: Arize Evaluation Model Name
                    type: object
                    ui:field: custom_dropdown
                    description: Select the Model
                    apiPath: /api/ai-components/models/?provider_id=3&model_type=LLM%20Model
                    attrKey: modelname
                    requiredData:
                      - key: region.value
                        queryStringKey: region_name
                        title: Region
                  
                  # arize_api_key_name:
                  #   title: Arize API Key Secret Name
                  #   type: string
                  #   description: Name of the secret in GCP Secret Manager that contains the Arize API Key
                
                  # arize_vertexai_integration_id:
                  #   title: Arize Vertexai Integration ID Secret in Key Vault
                  #   type: string
                  #   description: Provide Arize Vertexai Integration ID
                  #   ui:help: "The integration ID for linking Vertexai with Arize evaluations"

      required:
        # - arize_api_key_name
        # - arize_vertexai_integration_id  
        - arize_model_name     

    - title: Repository Details
      required:
        - repo_url
        - collaborators
      properties:
        repo_url:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
            - github.com
          # Enforce repo name length <= 56 (RepoUrlPicker value format: "github.com?owner=<org>&repo=<name>")
          pattern: "^github\\.com\\?owner=[^&]+&repo=[A-Za-z][A-Za-z0-9_-]{0,54}[A-Za-z0-9]$"
          errorMessage:
            pattern: "Repository name should start with a letter and end with an alphanumeric and can be at most 56 characters."
            
        default_branch:
          title: Default Branch
          type: string
          description: Provide the default branch name
          default: "main"
        protectDefaultBranch:
          title: Protect Default Branch
          type: boolean
          description: Whether to protect the default branch
          default: false
        collaborators:
          title: GitHub Team Collaborators
          type: array
          description: Name of the GitHub team to add as collaborators and the corresponding access level
          items:
            type: object
            properties:
              team:
                type: string
                title: Team Name
                description: Name of the Team in Github
              access:
                type: string
                title: Access Level
                description: Access level for the Team
                default: push
                enum:
                  - pull
                  - push
                  - admin
                  - maintain
                  - triage
          required:
            - team
            - access
  
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          agent_name: ${{ parameters.name }}
          agent_description: ${{ parameters.description }}
          agent_alias_name: ${{ parameters.agent_aliasname }}
          agent_alias_description: ${{ parameters.agent_aliasdescription }}
          model_name: ${{ parameters.llm_name.value }}
          instruction: ${{ parameters.instruction }}
          data_openapi_baseurl: ${{ scaffolder_globals.data_openapi_baseurl }}
          project_id: ${{ scaffolder_globals.gcp_project_id }}
          enable_guardrail: ${{ parameters.enable_guardrail }}
          guardrail_name: ${{ parameters.guardrail_name.value.guardrailname }}
          guardrailurl: ${{ parameters.guardrail_name.version.guardrailurl }}
          enable_groundtruth: ${{ parameters.enable_groundtruth }}
          enable_general_groundtruth: ${{ parameters.enable_general_groundtruth }}
          groundtruth_name: ${{ parameters.groundtruth.value.groundtruth_name }}
          groundtruth_model_name: ${{ parameters.groundtruth.version.modelname }}
          general_groundtruth_name: ${{ parameters.general_groundtruth.value.general_groundtruth_name }}
          general_groundtruth_model_name: ${{ parameters.general_groundtruth.value.modelname }}
          owner: ${{ parameters.owner }}
          staging_bucket_name: ${{ parameters.staging_bucket_name }}
          region: ${{ parameters.region.value }}
          lifecycle: ${{ parameters.lifecycle }}
          template_name: "gcp-agent"
          network_attachment: ${{ scaffolder_globals.gcp_network_attachment }}
          dns_peering_domain: ${{ scaffolder_globals.gcp_dns_peering_domain }}
          dns_peering_domain_target_project: ${{ scaffolder_globals.gcp_dns_peering_domain_target_project }}
          dns_peering_domain_target_network: ${{ scaffolder_globals.gcp_dns_peering_domain_target_network }}
          gcp_secret_manager_project: ${{ scaffolder_globals.gcp_project_number }}
          arize_model_name: ${{ parameters.arize_model_name.value }}
          arize_api_key_name: ${{ scaffolder_globals.arize_api_key_secret_name }}
          arize_space_id_name: ${{ scaffolder_globals.arize_space_id_secret_name }}
          arize_endpoint: ${{ scaffolder_globals.arize_endpoint }}
          arize_vertexai_integration_id_name: ${{ scaffolder_globals.arize_vertexai_integration_id_secret_name }}
          mcp_server_url: ${{ parameters.mcp_server_url.version.mcpurl }}

    - id: fetch-common
      name: Fetch Common Scripts
      action: fetch:template
      input:
        url: ../common/agent/evaluation
        targetPath: ./evaluation
        values:
          region: ${{ parameters.region.value }}
          project_id: ${{ scaffolder_globals.gcp_project_id }}
          gcp_secret_manager_project: ${{ scaffolder_globals.gcp_project_number }}
          arize_model_name: ${{ parameters.arize_model_name.value }}
          arize_api_key_name: ${{ scaffolder_globals.arize_api_key_secret_name }}
          arize_space_id_name: ${{ scaffolder_globals.arize_space_id_secret_name }}
          arize_endpoint: ${{ scaffolder_globals.arize_endpoint }}
          arize_vertexai_integration_id_name: ${{ scaffolder_globals.arize_vertexai_integration_id_secret_name }}
          general_groundtruth_model_name: ${{ parameters.general_groundtruth.value.modelname }}
          groundtruth_model_name: ${{ parameters.groundtruth.version.modelname }}

    - id: populate-rag-configuration
      name: Populate rag_configuration
      if: ${{ parameters.enable_rag }}
      action: fetch:template:file
      input:
        url: ./skeleton_rag_config/rag_configuration.json
        targetPath: ./src/rag_configuration.json
        values:
          rag_entities: ${{ parameters.rag_entities | dump }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: ${{ parameters.repo_url }}
        defaultBranch: "${{ parameters.default_branch }}"
        collaborators: ${{ parameters.collaborators }}
        protectDefaultBranch: ${{ parameters.protectDefaultBranch }}

    - id: apply-trigger
      name: Create GCP CloudBuild Trigger
      action: gcp:cloudbuild:create
      input:
        branchName: main
        githubRepositoryName: ${{ (parameters.repo_url | parseRepoUrl).repo }}
        githubRepositoryOwner: ${{ (parameters.repo_url | parseRepoUrl).owner }}
        triggerName: ${{ (parameters.repo_url | parseRepoUrl).repo | replace('_', '-') }}-trigger

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
