root_agent:
  project_id: "${{ values.project_id }}"
  region: "${{values.region}}"
  agent_display_name: "${{values.root_agent_display_name}}"
  agent_class: "${{values.root_agent_class}}"
  multiagent: "${{values.multiagent}}"
  model_id: "${{values.root_agent_model_id}}"
  description: "${{values.root_agent_description}}"
  guardrail_enabled: "${{values.enable_guardrail}}"
  guardrail_name: "${{values.root_agent_guardrail_name}}"
  guardrail_url: "${{values.root_agent_guardrailurl}}"
  guardrail_base_id: "${{values.root_agent_guardrail_base_id}}"
  enable_groundtruth: "${{ values.enable_groundtruth }}"
  enable_general_groundtruth: "${{ values.enable_general_groundtruth }}"
  groundtruth_name: "${{ values.groundtruth_name }}"
  general_groundtruth_name: "${{ values.general_groundtruth_name }}"
  arize_space_id_name: "${{ values.arize_space_id_name }}"
  arize_api_key_name: "${{ values.arize_api_key_name }}"
  arize_endpoint: "${{ values.arize_endpoint }}"
  arize_vertexai_integration_id_name: "${{ values.arize_vertexai_integration_id_name }}"
  gcp_secret_manager_project: "${{ values.gcp_secret_manager_project }}"
  global_instruction: 
    ${{ values.root_agent_instruction | dump }}
  instruction: 
    ${{ values.second_instruction | dump }}
  llm_config:          
    temperature: ${{values.temperature}}
    top_p: ${{values.top_p}}
    top_k: ${{values.top_k}}   
  agents: