"""Configuration management for GCP Vertex AI Agent."""

import os
from typing import Optional

import requests
from dotenv import load_dotenv
from .config_reader import ConfigReader
from utils.log_helper import setup_logging

load_dotenv()
logger = setup_logging()

# ---------------------------------------------------------------------------
# Agent identity — read from agent-config.yaml (generated by
# agent_config_generator.py from agents-config.json)
# ---------------------------------------------------------------------------
config = ConfigReader(os.path.join(os.path.dirname(__file__), "agent-config.yaml"))
root_agent = config.get_value("root_agent", {})

AGENT_DISPLAY_NAME = root_agent.get("name", "")
AGENT_DESCRIPTION = root_agent.get("description", "")
MODEL_NAME = root_agent.get("model", "")
SYSTEM_INSTRUCTION = root_agent.get("instruction", "")
AGENT_PROMPT = root_agent.get("prompt", "")
# OUTPUT_KEY = root_agent.get("output_key", None)

_gen_cfg = root_agent.get("generate_content_config", {})
TEMPERATURE = float(_gen_cfg.get("temperature", 0.28))
MAX_OUTPUT_TOKENS = int(_gen_cfg.get("max_output_tokens", 1000))
TOP_P = float(_gen_cfg.get("top_p", 0.95))

# ---------------------------------------------------------------------------
# Infrastructure — environment variables injected by Cloud Build substitutions
# ---------------------------------------------------------------------------
PROJECT_ID = os.getenv("PROJECT_ID")
LOCATION = os.getenv("LOCATION") or os.getenv("REGION")
REGION = LOCATION

DATA_APP_API_URL = os.getenv("DATA_APP_API_URL")
CLOUDRUN_SERVICE_URL = os.getenv("CLOUDRUN_SERVICE_URL")
SERVICE_ACCOUNT_NAME = os.getenv("SERVICE_ACCOUNT_NAME")

STAGING_BUCKET_NAME = os.getenv("STAGING_BUCKET_NAME", "")
STAGING_BUCKET = f"gs://{STAGING_BUCKET_NAME}" if STAGING_BUCKET_NAME else ""

MCP_SERVER_URL = os.getenv("MCP_SERVER_URL", "")

NETWORK_ATTACHMENT = os.getenv("NETWORK_ATTACHMENT")
DNS_PEERING_DOMAIN = os.getenv("DNS_PEERING_DOMAIN")
DNS_PEERING_DOMAIN_TARGET_PROJECT = os.getenv("DNS_PEERING_DOMAIN_TARGET_PROJECT")
DNS_PEERING_DOMAIN_TARGET_NETWORK = os.getenv("DNS_PEERING_DOMAIN_TARGET_NETWORK")

# ---------------------------------------------------------------------------
# Guardrail — environment variables
# ---------------------------------------------------------------------------
GUARDRAILS_ENABLED = os.getenv("GUARDRAILS_ENABLED", "false")
if isinstance(GUARDRAILS_ENABLED, str):
    GUARDRAILS_ENABLED = GUARDRAILS_ENABLED.strip().lower() == "true"

if GUARDRAILS_ENABLED:
    logger.info("🛡️ Guardrail is enabled.")
    GUARDRAIL_NAME = os.getenv("GUARDRAIL_NAME")
    GUARDRAIL_URL = os.getenv("GUARDRAIL_URL")
    GUARDRAIL_BUCKET_NAME = GUARDRAIL_URL.split("/")[3] if GUARDRAIL_URL else None
    GUARDRAIL_BUCKET_PREFIX = "/".join(GUARDRAIL_URL.split("/")[4:-1]) if GUARDRAIL_URL else None
    guardrail_file_name = GUARDRAIL_URL.split("/")[-1] if GUARDRAIL_URL else None
else:
    logger.info("❌ Guardrail is disabled.")
    GUARDRAIL_NAME = None
    GUARDRAIL_URL = None
    GUARDRAIL_BUCKET_NAME = None
    GUARDRAIL_BUCKET_PREFIX = None
    guardrail_file_name = None

# ---------------------------------------------------------------------------
# Evaluation — environment variables
# ---------------------------------------------------------------------------
ENABLE_GROUNDTRUTH = os.getenv("ENABLE_GROUNDTRUTH", "false").strip().lower() == "true"
if ENABLE_GROUNDTRUTH:
    logger.info("✅ Ground Truth is enabled.")
    GROUNDTRUTH_NAME = os.getenv("GROUNDTRUTH_NAME", "")
else:
    logger.info("❌ Ground Truth is disabled.")
    GROUNDTRUTH_NAME = None

ENABLE_GENERAL_GROUNDTRUTH = os.getenv("ENABLE_GENERAL_GROUNDTRUTH", "false").strip().lower() == "true"
if ENABLE_GENERAL_GROUNDTRUTH:
    logger.info("✅ General Ground Truth is enabled.")
    GENERAL_GROUNDTRUTH_NAME = os.getenv("GENERAL_GROUNDTRUTH_NAME", "")
else:
    logger.info("❌ General Ground Truth is disabled.")
    GENERAL_GROUNDTRUTH_NAME = None

GENERAL_EVALUATION = os.getenv("GENERAL_EVALUATION", "false")
GENERAL_EVALUATION_FILE = os.getenv("GENERAL_EVALUATION_FILE", "")
RAGAS_EVALUATION = os.getenv("RAGAS_EVALUATION", "false")
RAGAS_EVALUATION_FILE = os.getenv("RAGAS_EVALUATION_FILE", "")

# ---------------------------------------------------------------------------
# Arize observability — environment variables (secret names stored in GCP
# Secret Manager; the actual values are fetched at runtime in agent.py)
# ---------------------------------------------------------------------------
ARIZE_SPACE_ID_NAME = os.getenv("ARIZE_SPACE_ID_NAME", "")
ARIZE_API_KEY_NAME = os.getenv("ARIZE_API_KEY_NAME", "")
ARIZE_ENDPOINT = os.getenv("ARIZE_ENDPOINT", "")
GCP_SECRET_MANAGER_PROJECT = os.getenv("GCP_SECRET_MANAGER_PROJECT", "")
