import os
import vertexai
import dotenv

from dotenv import dotenv_values
dotenv.load_dotenv()
from config.config import (
    # Infrastructure — from environment variables
    PROJECT_ID,
    LOCATION,
    GENERAL_EVALUATION,
    RAGAS_EVALUATION,
    # Agent definition — from agent-config.yaml (generated by agent_config_generator.py)
    AGENT_DISPLAY_NAME,
    AGENT_DESCRIPTION,
    MODEL_NAME,
    SYSTEM_INSTRUCTION,
    AGENT_PROMPT,
    TEMPERATURE,
    MAX_OUTPUT_TOKENS,
    TOP_P,
)

from utils.log_helper import setup_logging
logger = setup_logging()

from google.cloud.aiplatform import initializer
from google.genai import types
from google.adk.agents import Agent
from vertexai import agent_engines
from load_rag_corpora import get_corpus_as_tools
from load_mcp_tools import load_mcp_toolset
from content_filter.safety_settings import safety_settings_download_callback, safety_settings_model_callback

# Extract values from configuration
agent_display_name = AGENT_DISPLAY_NAME
agent_description = AGENT_DESCRIPTION
model = MODEL_NAME
system_instruction = SYSTEM_INSTRUCTION
prompt = AGENT_PROMPT


logger.info(f"Value of GENERAL_EVALUATION: {GENERAL_EVALUATION}")
logger.info(f"Value of RAGAS_EVALUATION: {RAGAS_EVALUATION}")

# Initialize Vertex AI SDK
logger.info("🔧 Initializing Vertex AI SDK...")
vertexai.init(project=PROJECT_ID, location=LOCATION)

final_tools = []
final_tools.extend(get_corpus_as_tools("rag_configuration.json"))

# Load MCP toolset if configured
mcp_toolset = load_mcp_toolset()
if mcp_toolset is not None:
    final_tools.append(mcp_toolset)

# Define the agent.
# provide the model name, the tools either functional or rag,
# and the instruction and prompts.
agent = None

llm_config = {
    "config_list": [{
        "project_id":       PROJECT_ID,
        "location":         LOCATION,
        "model":            model,
        "api_type":         "google",
    }]
}
generate_content_config = types.GenerateContentConfig(
    temperature=TEMPERATURE,
    max_output_tokens=MAX_OUTPUT_TOKENS,
    top_p=TOP_P,
)
agent = Agent(
    model=model,
    name=agent_display_name,
    generate_content_config=generate_content_config,
    tools=final_tools,
    before_agent_callback=safety_settings_download_callback,
    before_model_callback=safety_settings_model_callback,
    instruction=system_instruction,

)

# Wrap agent in AdkApp (required for deployment)
logger.info(f"📦 Wrapping agent '{agent_display_name}' in AdkApp...")
app = agent_engines.AdkApp(
    agent=agent,
    enable_tracing=True,
)

