site_name: ${{ values.root_agent_display_name }}
site_description: Multi-Agent Orchestrator on GCP

# Configuration
theme:
  name: material
  palette:
    primary: blue
    accent: light blue

# Plugins
plugins:
  - search
  - techdocs-core

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences

# Navigation
nav:
  - Home: index.md
