apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Created with ${{ values.template_name }} Template. ${{ values.description }}
  tags:
    - gcp
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: vertexai-agent-client
  owner: ${{ values.owner }}
  lifecycle: ${{ values.lifecycle }}