steps:

  - name: 'python:3.12'
    entrypoint: 'bash'
    dir: 'src'
    args:
      - '-c'
      - |
        pip install uv
        uv venv
        source .venv/bin/activate
        uv run agent_client.py
substitutions:
  _WORKER_POOL_NAME: ''
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: ${_WORKER_POOL_NAME}
